//! Parse Cargo.lock to extract dependency names and versions.

use anyhow::{Context, Result};
use std::path::Path;

/// A single package entry from Cargo.lock.
#[derive(Debug, Clone)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
}

/// Parse a Cargo.lock file and return all locked packages.
///
/// Supports both Cargo.lock v1/v2/v3 formats — they all use the same
/// `[[package]]` table-array structure for the fields we care about.
pub fn parse_lockfile(path: &Path) -> Result<Vec<LockedPackage>> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("reading {}", path.display()))?;

    let parsed: toml::Value =
        toml::from_str(&content).with_context(|| format!("parsing {}", path.display()))?;

    let packages = parsed
        .get("package")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|pkg| {
                    let name = pkg.get("name")?.as_str()?.to_string();
                    let version = pkg.get("version")?.as_str()?.to_string();
                    Some(LockedPackage { name, version })
                })
                .collect()
        })
        .unwrap_or_default();

    Ok(packages)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn test_parse_lockfile() {
        let mut tmp = tempfile::NamedTempFile::new().unwrap();
        write!(
            tmp,
            r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "hyper"
version = "0.14.27"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.32.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "my-app"
version = "0.1.0"
"#
        )
        .unwrap();

        let packages = parse_lockfile(tmp.path()).unwrap();
        assert_eq!(packages.len(), 3);
        assert_eq!(packages[0].name, "hyper");
        assert_eq!(packages[0].version, "0.14.27");
        assert_eq!(packages[1].name, "tokio");
        assert_eq!(packages[1].version, "1.32.0");
    }
}
